spring.application.name=geotracker-backend
#server.port=8080
spring.profiles.active=dev

#spring.data.mongodb.uri=mongodb://localhost:27017/geotracker
spring.data.mongodb.uri=mongodb+srv://athawaleyashdadarao_db_user:YashAtlas2505@geotracker.fxo2ey0.mongodb.net/geotracker?retryWrites=true&w=majority
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27019
#spring.data.mongodb.database=geotracker
spring.security.user.name=admin
spring.security.user.password=pass

jwt.secret=MySuperSecretKey123456
jwt.expiration=86400000
